---
- name: Instalar pexpect y cambiar la contraseña de root
  hosts: cliente11
  become: yes
  vars:
    new_root_password: "000000"
  tasks:
    - name: Instalar pexpect en sistemas RedHat
      dnf:
        name: python3-pexpect
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Instalar pexpect en sistemas Debian
      apt:
        name: python3-pexpect
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Cambiar la contraseña de root con expect
      ansible.builtin.expect:
        command: passwd root
        responses:
          '(?i)(new password:|nueva contraseña:)': "{{ new_root_password }}"
          '(?i)(retype new password:|vuelva a escribir la nueva contraseña:|reintroduzca la nueva contraseña:)': "{{ new_root_password }}"
        timeout: 30
      no_log: true


