---
- hosts: cliente12
  tasks:
    - name: Install cockpit
      yum:
        name: "{{ item }}"
        state: present
      with_items:
      - cockpit*
# start and enable cockpit
    - name: start cockpit
      systemd:
        name: cockpit
        state: started
