---
- name: Install docker Centos
  gather_facts: No
  hosts: clientes
  user: root
  tasks:
    - name: paquetes
      yum:
        name: "{{  item  }}"
        state: latest
      loop:
       - php
       - mc
