---
- name: Update Linux systems and install packages
  hosts: localhost
  become: yes  # Escalado de privilegios para ejecutar tareas administrativas
  tasks:
    - name: Update all packages to the latest version
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"  

    - name: Remove unnecessary packages
      ansible.builtin.dnf:
        autoremove: yes
      when: ansible_os_family == "RedHat"  


    - name: Install packages on RedHat-based systems
      ansible.builtin.yum:
        name:
          - bash-completion
          - git
          - mc
        state: present
      when: ansible_os_family == "RedHat"

    - name: Update all packages on Debian-based systems
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Install packages on Debian-based systems
      ansible.builtin.apt:
        name:
          - bash-completion
          - git
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Instalar el paquete chrony
      dnf:
        name: chrony
        state: present

    - name: Configurar el archivo de configuraci贸n de chrony
      blockinfile:
        path: /etc/chrony.conf
        create: yes
        block: |
          # Servidores NTP recomendados
          server hora.roa.es iburst
          server minuto.roa.es iburst
          # Permitir la sincronizaci贸n de tiempo de la red local
          allow 192.168.0.0/24
          # Local stratum 10
          local stratum 10
          # Drift file
          driftfile /var/lib/chrony/drift
          # Command port
          cmdport 0

    - name: Habilitar y iniciar el servicio chronyd
      systemd:
        name: chronyd
        enabled: true
        state: started

    - name: Verificar el estado de la sincronizaci贸n
      command: chronyc tracking
      register: chrony_tracking

    - name: Mostrar el estado de la sincronizaci贸n
      debug:
        var: chrony_tracking.stdout

    - name: Cambiar zona horaria
      command: timedatectl set-timezone Europe/Madrid
      register: timedatectl_output

    - name: Cambiar Lang
      command: localectl set-locale LANG=es_ES.utf8
      register: localectllang_output

    - name: Cambiar keymap
      command: localectl set-keymap es
      register: localectlkeymap_output

    - debug: var=timedatectl_output
    - debug: var=localectllang_output
    - name: Printar solo la salida lines de la tarea el return control
      debug: var=localectlkeymap_output.rc
