---
- name: Update Linux systems and install packages
  hosts: localhost
  become: yes  # Escalado de privilegios para ejecutar tareas administrativas
  tasks:
    - name: Update all packages to the latest version
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"  

    - name: Remove unnecessary packages
      ansible.builtin.dnf:
        autoremove: yes
      when: ansible_os_family == "RedHat"  

    - name: Clean all cached packages
      ansible.builtin.dnf:
        clean: all
      when: ansible_os_family == "RedHat"  

    - name: Install packages on RedHat-based systems
      ansible.builtin.yum:
        name:
          - bash-completion
          - git
        state: present
      when: ansible_os_family == "RedHat"

    - name: Update all packages on Debian-based systems
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Install packages on Debian-based systems
      ansible.builtin.apt:
        name:
          - bash-completion
          - git
        state: present
      when: ansible_os_family == "Debian"

