- name: Desmontar NFS y eliminar la entrada en /etc/fstab
  hosts: cliente12
  become: yes
  tasks:
    - name: Verificar si /share está montado
      shell: mount | grep "/share"
      register: mount_check
      ignore_errors: yes
      changed_when: false

    - name: Desmontar el recurso NFS si está montado
      ansible.builtin.command:
        cmd: umount /share
      when: mount_check.rc == 0

    - name: Eliminar la línea de montaje NFS en /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^192\.168\.33\.11:/share/folder /share nfs defaults 0 0$'
        state: absent
