options {
 directory "/var/named";
 forwarders{
  8.8.8.8;
  8.8.4.4;
   
 };

};

 
zone "." {
 type hint;
 file "named.ca";
};
zone "curso.esp"{
 type slave;
 file "slaves/db.curso";
 masters { 192.168.2.5; };
};
 
zone "2.168.192.IN-ADDR.ARPA"{
 type slave;
 file "slaves/db.192.168.2";
 masters { 192.168.2.5; };
  
};

