- name: Install and configure haproxy
  hosts: 192.168.33.11
  become: true
  become_method: sudo
  tasks:
    - name: Install haproxy
      package:
        name: haproxy
        state: latest
    - name: Copy configuration file for haproxy
      template:
        src: haproxy.j2
        dest: /etc/haproxy/haproxy.cfg
    - name: Start and enable haproxy
      service:
        name: haproxy
        state: restarted
        enabled: true 
